- hosts: all
  tasks:
    - name: "Add web app to hosts"
      lineinfile:
        state: present
        dest: /etc/hosts
        line: 127.0.0.1       websecurity.tutorial.com

    - name: "Add openam to hosts"
      lineinfile:
        state: present
        dest: /etc/hosts
        line: 192.168.56.11 openam.example.com openidm.example.com

