- hosts: all
  tasks:
    - name: "Add web app to hosts"
      lineinfile:
        state: present
        dest: /etc/hosts
        line: 127.0.0.1       websecurity.tutorial.com

    - name: "Add auth service  hosts"
      lineinfile:
        state: present
        dest: /etc/hosts
        line: 127.0.0.1       auth.websecurity.tutorial.com

    - name: "Add csrf application to hosts"
      lineinfile:
        state: present
        dest: /etc/hosts
        line: 127.0.0.1       banking.example.com

    - name: "Add evil hacker to hosts"
      lineinfile:
        state: present
        dest: /etc/hosts
        line: 127.0.0.1       hacker.com


    - name: "Add openam to hosts"
      lineinfile:
        state: present
        dest: /etc/hosts
        line: 192.168.56.11 openam.example.com openidm.example.com

